In [1]:
import pandas as pd

In [2]:
whr_df = pd.read_excel('WHR.xlsx')

In [3]:
whr_df.head()

,Year,Rank,Country name,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2025,1,Finland,7.764,7.690,7.837,1.915,1.638,0.939,1.105,0.093,0.491,1.582
1,2025,2,Iceland,7.540,7.449,7.630,1.971,1.720,0.996,1.105,0.187,0.187,1.373
2,2025,3,Denmark,7.539,7.446,7.631,1.986,1.633,0.930,1.081,0.125,0.474,1.310
3,2025,4,Costa Rica,7.439,7.356,7.522,1.697,1.483,0.739,1.101,0.059,0.122,2.236
4,2025,5,Sweden,7.255,7.172,7.337,1.950,1.570,1.027,1.070,0.149,0.447,1.041

In [4]:
whr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2116 entries, 0 to 2115
Data columns (total 13 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        2116 non-null   int64
 1   Rank                                        2116 non-null   int64
 2   Country name                                2116 non-null   object
 3   Life evaluation (3-year average)            2116 non-null   float64
 4   Lower whisker                               1022 non-null   float64
 5   Upper whisker                               1022 non-null   float64
 6   Explained by: Log GDP per capita            1019 non-null   float64
 7   Explained by: Social support                1019 non-null   float64
 8   Explained by: Healthy life expectancy       1016 non-null   float64
 9   Explained by: Freedom to make life choices  1017 non-null   float64
 10  Explained by: Generosity                    1019 non-null   float64
 11  Explained by: Perceptions of corruption     1018 non-null   float64
 12  Dystopia + residual                         1013 non-null   float64
dtypes: float64(10), int64(2), object(1)
memory usage: 215.0+ KB

In [5]:
whr_df.dropna(subset=['Lower whisker'], inplace=True)

In [6]:
whr_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1022 entries, 0 to 1021
Data columns (total 13 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        1022 non-null   int64
 1   Rank                                        1022 non-null   int64
 2   Country name                                1022 non-null   object
 3   Life evaluation (3-year average)            1022 non-null   float64
 4   Lower whisker                               1022 non-null   float64
 5   Upper whisker                               1022 non-null   float64
 6   Explained by: Log GDP per capita            1019 non-null   float64
 7   Explained by: Social support                1019 non-null   float64
 8   Explained by: Healthy life expectancy       1016 non-null   float64
 9   Explained by: Freedom to make life choices  1017 non-null   float64
 10  Explained by: Generosity                    1019 non-null   float64
 11  Explained by: Perceptions of corruption     1018 non-null   float64
 12  Dystopia + residual                         1013 non-null   float64
dtypes: float64(10), int64(2), object(1)
memory usage: 111.8+ KB

In [7]:
whr_df.value_counts('Country name')

Country name
Afghanistan                 7
Kyrgyzstan                  7
Myanmar                     7
Namibia                     7
Nepal                       7
                           ..
Haiti                       2
Maldives                    2
Burundi                     2
Central African Republic    1
South Sudan                 1
Name: count, Length: 157, dtype: int64

In [8]:
whr_df.describe()

,Year,Rank,Life evaluation (3-year average),Lower whisker,Upper whisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
count,1022.000000,1022.000000,1022.000000,1022.000000,1022.000000,1019.000000,1019.000000,1016.000000,1017.000000,1019.000000,1018.000000,1013.000000
mean,2021.975538,73.573386,5.550427,5.436091,5.664733,1.265670,1.096746,0.553435,0.609465,0.147343,0.144911,1.736935
std,2.021527,42.291651,1.123618,1.140959,1.107424,0.463823,0.357642,0.229980,0.212070,0.084335,0.118803,0.657497
min,2019.000000,1.000000,1.364000,1.301000,1.427000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.295000
25%,2020.000000,37.000000,4.745650,4.619707,4.867750,0.944000,0.865000,0.389750,0.471000,0.088000,0.063156,1.305000
50%,2022.000000,73.500000,5.705000,5.592631,5.812000,1.304000,1.140119,0.560500,0.602000,0.134000,0.113000,1.765000
75%,2024.000000,110.000000,6.377775,6.290110,6.486500,1.636000,1.382000,0.712325,0.735000,0.195477,0.181330,2.178000
max,2025.000000,153.000000,7.842000,7.780000,7.904000,2.209000,1.840000,1.238000,1.147000,0.569814,0.587000,3.482000

In [9]:
country_counts = whr_df["Country name"].value_counts()

In [10]:
whr_filtered = whr_df[whr_df["Country name"].isin(country_counts[country_counts >= 7].index)]

In [12]:
whr_filtered.value_counts('Country name')

Country name
Afghanistan    7
Norway         7
Netherlands    7
New Zealand    7
Nicaragua      7
              ..
France         7
Finland        7
Ethiopia       7
Estonia        7
Zimbabwe       7
Name: count, Length: 136, dtype: int64

In [13]:
whr_filtered.to_excel("whr_cleaned.xlsx", index=False)